# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockAlert' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'TwitterKit'
  pod 'Alamofire'
  pod 'SnapKit'
  # Pods for StockAlert

end
